### ISSUE TITLE
I don't want to use exceptions

### ISSUE THREAD

**Issue by DavideBassano** [sreiter/stl_reader#1]
Hello, thanks for your code.

> Note: If you do not want to use exceptions, you may define the macro STL_READER_NO_EXCEPTIONS before including 'stl_reader.h'. In that case, functions will return false if an error occurred.

Could you be a bit more specific? How do I define the macro? Where do I define it?

Thanks,
Cheers,

Davide Bassano

**Comment by sreiter** [comment]
Hi Davide,
the most simple way would be:
```
#define STL_READER_NO_EXCEPTIONS
#include "stl_reader.h"
```
If you're e.g. using cmake as a build system for your project, you could instead add the following line to your CMakeLists.txt:
`ADD_DEFINITIONS(-DSTL_READER_NO_EXCEPTIONS)`

Hope this helps!
Kind regards,
Sebastian
