### ISSUE TITLE
Would using tolerance value for vertex co-ordinate comparisons be safer?

### ISSUE THREAD

**Issue by aerosayan** [sreiter/stl_reader#12]
Hello,

Thanks for creating the library. It's very helpful.

I noticed that the library is using exact comparisons (`==` and `!=`) for the vertex co-ordinates.

```c++
    bool operator==(const CoordWithIndex & c) const
    {
        return (c[0] == data[0]) && (c[1] == data[1]) && (c[2] == data[2]);
    }

   bool operator!=(const CoordWithIndex & c) const
    {
        return (c[0] != data[0]) || (c[1] != data[1]) || (c[2] != data[2]);
    }
```

Since the co-ordinate data will be floating point numbers, this might cause a random floating point error, and the comparisons may give a wrong result in the form of either a false positive or false negative result.

Would you be okay with using a tolerance value for these comparisons?

Example: Instead of the equal `==` comparison, we can use:

```c++
 bool operator==(const CoordWithIndex & c) const
{
    const double tolerance = 1E-9;
    const bool result_x = (std::abs(c[0]-data[0])<=tolerance);
    const bool result_y = (std::abs(c[1]-data[1])<=tolerance);
    const bool result_z = (std::abs(c[2]-data[2])<=tolerance);
    return (result_x && result_y && result_z);
}
```

The tolerance value can be set by you, but it's best if the user can change it. They might use 1E-6 or 1E-3 for instance.

Thanks

**Comment by sreiter** [comment]
Thanks for the nice words!

While I agree that floating point comparisons are problematic in general, I think the exact comparison is actually fine in this case. The different triangles actually refer to the exact same vertices and one can thus expect programs to write the exact same coordinates whenever such a vertex is referred to.

Clustering close vertices using a threshold is unfortunately a bit more complex than just adding a tolerance to the equality operator. After all, we do the equality check after sorting. And after sorting, close vertices may actually not be located next to each other in the sorted list. So a bit more work would be required here.

Did you encounter stl files where this is an issue? Or is this more a theoretical concern?

Kind regards,
Sebastian
