### ISSUE TITLE
Missing Triangles

### ISSUE THREAD

**Issue by sharjith** [sreiter/stl_reader#2]
Thanks for the library.
I have tested with various STL files. But all of them have missing triangles.

Please see screenshots of Expected vs Result.

![Expected](https://user-images.githubusercontent.com/667228/85927278-a2a35200-b8c2-11ea-906f-e3696070717e.png)
![Result](https://user-images.githubusercontent.com/667228/85927280-a9ca6000-b8c2-11ea-900b-9f00b0bd06bf.png)

Please see the test data attached below.

[pump.zip](https://github.com/sreiter/stl_reader/files/4840920/pump.zip)

**Comment by sreiter** [comment]
Hi,
thanks for your feedback! I checked your stl-file with the most recent version of the stl_reader, but I couldn't find any problems. Here is a screenshot - I think all triangles are there.
![pump_screenshot](https://user-images.githubusercontent.com/5648216/85956054-2a509580-b983-11ea-9cad-51b3a4763c71.png)
The code I used just uses all triangles specified in the returned triangles array (essentially sample 3 from the stl_reader github page).
Maybe I could help identify the issue if you share your importer code?
Thanks and kind regards,
Sebastian

**Comment by sharjith** [comment]
I have used the same code. But even before I make use of the triangles, I simply tested for the number of triangles that it reads. It is showing less number of triangles that actually it has. Then I commented out the RemoveDoubles method and the number of triangles is coming correct. Please see attached screenshots below (before and after commenting out RemoveDoubles).

Before commenting
![Screenshot_20200629_122032](https://user-images.githubusercontent.com/667228/85982899-39c3f300-ba04-11ea-97db-c6c9b7f32686.png)

After commenting
![Screenshot_20200629_122115](https://user-images.githubusercontent.com/667228/85982949-48aaa580-ba04-11ea-8916-f18ff7941b98.png)

**Comment by sreiter** [comment]
Thanks again for your feedback. There have been 6 triangles removed. During `RemoveDoubles` vertices which have identical positions are merged. If a triangle referenced two vertices with identical positions, this triangle would collapse to a line segment after the vertex merge. Such degenerate triangles are not considered as valid triangles and are thus removed. Such triangles have no effect on the visualization and their removal does not produce holes. I admit that the behavior may be slightly surprising, however, keeping those degenerate triangles typically result in issues in algorithms down the road.

Nevertheless, I guess that even after disabling `RemoveDoubles`, the visual appearance did not change and that you still didn't see the whole geometry. My guess would be that you do not copy all triangle indices into your rendering structures or that you maybe pass a wrong `count` to the glDrawElements method.

Please let me know if your issue persists.
Kind regards,
Sebastian

**Comment by sharjith** [comment]
Thanks for the detailed response. I now get what the issue is. My function of initializing buffers requires the indices, vertices, and normals to be passed into it. However, the number of normals expected is equal to the number of vertices. So, I tried passing the outputs from your function directly to the initBuffer function, all the triangles are rendered but since the number of normals does not match the vertices, the lighting becomes bad. Like in the image below.

![Screenshot_20200630_113124](https://user-images.githubusercontent.com/667228/86089161-57a55c80-bac5-11ea-9001-4963aa6a3532.png)

Hence if I try to get the individual triangles from the loop shown in the example code and also the normals (plus adding the same normal two more times to the vector) and using the itri variable to add to the indices, all works well except for the missing triangles as I reported originally.

For all the other geometric objects for which I am creating the vertices and normals programmatically, I am able to achieve it with per-vertex normals.
I need to figure out how I can send the vertices, normals, and indices to OpenGL in this case. Any suggestion will be really helpful

Thanks and Regards,
Sharjith

**Comment by sharjith** [comment]
The issue can be closed since the library works as designed. Although, some help on using it to pass to OpenGL functions will be great!

**Comment by sreiter** [comment]
Hi Sharjith,

I assembled a small code snippet which illustrates how one can compute vertex normals from triangle normals both for smooth and for flat shading:

https://gist.github.com/sreiter/b6a4a834b65ecc715cd0f11b62b7e4b8

Please note that the snippet there has not been compiled and may contain some small issues. I still hope it illustrates the idea well enough.

Hope this helps,
Kind regards,
Sebastian
