### ISSUE TITLE
StlFileHasASCIIFormat does not correctly guess stl binary types

### ISSUE THREAD

**Issue by charkops** [sreiter/stl_reader#3]
As it turns out, when exporting a mesh from SolidWorks (as a binary stl), the binary header starts with the word "solid"...
And after looking at the code in stl_reader which decides if the input file is ascii || binary i see that the decision is based on the first word of the input file. This causes some files (maybe all of them since this is the default SolidWorks behaviour) to crash programms trying to read them with this library.

Do you have any idea of how else to distinguish ascii from binary stl files ? 
I am happy to submit a PR fixing this if we come to a solution

**Comment by sreiter** [comment]
Hey, thanks for raising the issue.

If you could provide a small sample file I will take a look at it. I think it should be possible to slightly extend the check.

Thanks!

**Comment by charkops** [comment]
Sorry for taking so long to respond, 
[cube.zip](https://github.com/sreiter/stl_reader/files/5456835/cube.zip)

this is a small cube i tried to read, but the problem remains on all binary stl files exported with SolidWorks.

According to this thread: https://forum.solidworks.com/thread/232016 
they are aware of the issue but they don't seem to really care about it.

**Comment by sreiter** [comment]
Thanks for providing the example file.
I slightly adjusted the detection of ASCII/binary files. This should fix your issue while hopefully still correctly guessing files exported from other applications.
It would be great if you could check whether the fix works for you.
Regards

**Comment by sreiter** [comment]
I will close this issue for now. Should similar issues pop up, please open a new issue. Thanks :)
