### ISSUE TITLE
RemoveDoubles does not update the solidRanges datastructure

### ISSUE THREAD

**Issue by sisirajaya** [sreiter/stl_reader#5]
Reffer to comment in line 492 "            //  make sure to only add triangles which refer to three different indices"

When this happens the facets get removed from the trisInOut . Therefore the solidRanges array must be adjusted accordingly.

Especially, it the STL file has multiple solids.

I have fixed this and I have stl_reader.h with that fix.
[stl_reader.zip](https://github.com/sreiter/stl_reader/files/9888515/stl_reader.zip)

Also I have added vector solid_names to store the name defined in solid statement for ASCII and a default string for BINARY.

**Comment by sreiter** [comment]
Thanks a lot for your comment and the fix you offered. Honestly, I hesitate a bit to open a zip file from an unknown source. Would you mind creating a merge request for your changes? That would be greatly appreciated! 😃

**Comment by sisirajaya** [comment]
Hi:

I am new to Git . I  am a perforce, clearcase etc etc user. I could not make a merge request and that is why I created what I could. It only accepted zip files. Since Git took it ok you can trust that I did not put anything in it.

 

I attached the header file here.

 

Thank you.

Sisira

**Comment by sreiter** [comment]
Hi Sisira,
thank's again for raising the issue and for providing a fix. I wasn't aware of the zip limitation. I will check out the header you attached.
Thank's and kind regards,
Sebastian

**Comment by sreiter** [comment]
I finally resolved the issue... Thanks again for providing feedback!
