### ISSUE TITLE
when degenerated triangles were removed the normalOut data is not updated  simultaneously

### ISSUE THREAD

**Issue by leonaiverson** [sreiter/stl_reader#8]
function RemoveDoubles need fixing cuz when degenerated triangles were removed the normalOut data is not updated  simultaneously

**Comment by sreiter** [comment]
Thanks for your feedback. I will have a look at it!

**Comment by sreiter** [comment]
I adjusted `RemoveDoubles` so that both normals and solids are now kept in sync when degenerated triangles are removed. Thanks again for your feedback.
