### ISSUE TITLE
bug in removeDoubles

### ISSUE THREAD

**Issue by leonaiverson** [sreiter/stl_reader#9]
line 476  newIndex[0]=0 seems a bug 
fix suggest:
     newIndex[coordsWithIndexInOut[0].index]=0;

by the way i have a proposal:
    stl_mesh need to extend its removeDoubles  to work in the condition that removing duplicate point and degenerate triangles in each solid ,the data in each solid have no influence with eachother.

**Comment by sreiter** [comment]
Hi, thanks for your comment. There was indeed a bug in line 476. Thanks for pointing it out!
I also adjusted the `RemoveDoubles` function and added some tests.
